sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    
# addon:
#  apt:
#    packages:
#      - libxxf86vm-dev
#      - libosmesa6-dev
#      - libcurl4-openssl-dev      # for kcov
#      - libelf-dev                # for kcov
#      - libdw-dev                 # for kcov
#      - cmake                     # for kcov

# script:
    # We run everything with `-j 1` or travis runs out of memory
    #- cargo build -v --no-default-features --features "$FEATURES"
    #- if [ "$TEST" -eq 1 ]; then cargo test -v -j 1 --no-default-features --features "$FEATURES"; fi
#    - cargo test -v -j 1 --no-default-features --features "integration"
  
# after_success: |
#  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
#        tar xzf master.tar.gz &&
#        mv kcov-master kcov &&
#        mkdir kcov/build &&
#        cd kcov/build &&
#        cmake .. &&
#        make &&
#        make install && 
#        cd ../.. &&
#        kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/runner_game-*
