[package]
name = "runner_game"
version = "0.2.0"
authors = ["romain <assie.romain@gmail.com>"]

[dependencies]
glium="0.17.1"
image="0.16.0"
time = "0.1"
rand = "0.3"
cgmath = "*"
# winapi = "*"
# gilrs = "0.1.0"
rodio = "*"
xml-rs = "0.7"


[features]
integration=[]
