[package]
name = "runner_game"
version = "0.2.0"
authors = ["romain <assie.romain@gmail.com>"]

[dependencies]
glium="*"
image="0.12.3"
time = "0.1"
rand = "0.3"
# winapi = "*"
# gilrs = "0.1.0"


[features]
integration=[]
